import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { GlobalCssPriority } from '~/common/components/templates/material/MaterialCacheLayout';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '~/styles/globals.scss';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* //? for material ui */}
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <GlobalCssPriority>{children}</GlobalCssPriority>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
